21-09-12 jstl 종합문제2
There was an unexpected error (type=Internal Server Error, status=500).
Cannot invoke "com.quiz.lesson05.bo.NewReviewBO.getNewReviewByStoreId(int)" because "this.newReviewBO" is null
java.lang.NullPointerException: Cannot invoke "com.quiz.lesson05.bo.NewReviewBO.getNewReviewByStoreId(int)" because "this.newReviewBO" is null